"""
Phase 6 - Throughput validation against a known ground truth
==================================================================

Why this phase exists
-----------------------
Every earlier phase reported bandwidth/packet-rate numbers computed by
this project's own capture engine, and those numbers were trusted at
face value - useful for relative comparisons (baseline vs. scan) but
never checked against an independently measured ground truth. This
script compares the capture engine's own observed bandwidth against a
known, precisely measured reference throughput, producing an actual
accuracy figure (percentage error) rather than an assumption that the
metrics are correct.

Input format
-------------
This script reads a JSON file describing a series of timed intervals,
each with a known reference "bits_per_second" and an absolute start
time. This format is intentionally the same shape iperf3 produces with
its -J flag - so this script works unchanged whether the ground-truth
traffic was generated by iperf3, or by this project's own
loadgen.py (a small pure-Python throughput generator built specifically
to avoid requiring an iperf3 installation - see loadgen.py's own
docstring). Neither tool is a hard dependency of this script; it only
depends on the JSON shape.

How the comparison works
--------------------------
    1. Parse the ground-truth JSON, converting each interval's relative
       start/end offsets into absolute Unix timestamps using the
       recorded test start time.
    2. Query window_metrics for rows whose [window_start, window_end]
       range overlaps that interval at all.
    3. Where more than one window_metrics row overlaps a single
       interval (or only partially overlaps it), compute a
       duration-weighted average of the observed bandwidth across the
       overlapping portion, so a window that only partially overlaps
       an interval contributes proportionally rather than being
       double-counted or ignored.
    4. Report, per interval: the reference Mbps, the capture engine's
       observed Mbps, and the percentage error between them.

Usage
-----
    # Using this project's own loadgen.py (no external tools required):
    python loadgen.py --duration 30 --interval 5 --output loadgen_result.json
    python throughput_compare.py --json loadgen_result.json --db netmon.db

    # Or, if iperf3 is available and preferred instead:
    iperf3 -c 127.0.0.1 -t 30 -i 5 -J > iperf_result.json
    python throughput_compare.py --json iperf_result.json --db netmon.db
"""

import argparse
import json
import sqlite3
from dataclasses import dataclass


@dataclass
class ReferenceInterval:
    start: float  # absolute unix timestamp
    end: float
    expected_mbps: float


@dataclass
class ComparisonRow:
    interval: ReferenceInterval
    observed_mbps: float | None  # None if no overlapping window_metrics data found
    overlap_seconds: float
    error_pct: float | None


def parse_ground_truth_json(path: str) -> list[ReferenceInterval]:
    """Parse iperf3's -J output into a list of intervals with absolute
    timestamps. Handles the standard client-side JSON structure."""
    with open(path) as f:
        data = json.load(f)

    test_start_unix = data["start"]["timestamp"]["timesecs"]

    intervals = []
    for interval in data["intervals"]:
        s = interval["sum"]
        abs_start = test_start_unix + s["start"]
        abs_end = test_start_unix + s["end"]
        expected_mbps = s["bits_per_second"] / 1_000_000
        intervals.append(ReferenceInterval(start=abs_start, end=abs_end, expected_mbps=expected_mbps))
    return intervals


def overlap_seconds(a_start: float, a_end: float, b_start: float, b_end: float) -> float:
    """Duration, in seconds, that two [start, end) ranges overlap. 0 if none."""
    return max(0.0, min(a_end, b_end) - max(a_start, b_start))


def load_window_metrics(conn: sqlite3.Connection) -> list[dict]:
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    cur.execute("SELECT window_start, window_end, bandwidth_mbps FROM window_metrics ORDER BY window_start")
    return [dict(r) for r in cur.fetchall()]


def compare(intervals: list[ReferenceInterval], windows: list[dict]) -> list[ComparisonRow]:
    results = []
    for interval in intervals:
        total_overlap = 0.0
        weighted_bandwidth_sum = 0.0

        for w in windows:
            ov = overlap_seconds(interval.start, interval.end, w["window_start"], w["window_end"])
            if ov > 0:
                weighted_bandwidth_sum += w["bandwidth_mbps"] * ov
                total_overlap += ov

        if total_overlap > 0:
            observed_mbps = weighted_bandwidth_sum / total_overlap
            error_pct = 100.0 * (observed_mbps - interval.expected_mbps) / interval.expected_mbps
        else:
            observed_mbps = None
            error_pct = None

        results.append(ComparisonRow(
            interval=interval, observed_mbps=observed_mbps,
            overlap_seconds=total_overlap, error_pct=error_pct,
        ))
    return results


def print_report(results: list[ComparisonRow]) -> None:
    print(f"{'interval':>18}  {'expected(Mbps)':>15}  {'observed(Mbps)':>15}  "
          f"{'overlap(s)':>10}  {'error(%)':>9}")
    errors = []
    for r in results:
        dur = r.interval.end - r.interval.start
        label = f"{dur:.0f}s window"
        if r.observed_mbps is None:
            print(f"{label:>18}  {r.interval.expected_mbps:>15.3f}  {'no data':>15}  "
                  f"{r.overlap_seconds:>10.2f}  {'--':>9}")
        else:
            print(f"{label:>18}  {r.interval.expected_mbps:>15.3f}  {r.observed_mbps:>15.3f}  "
                  f"{r.overlap_seconds:>10.2f}  {r.error_pct:>8.1f}%")
            errors.append(abs(r.error_pct))

    if errors:
        print(f"\nIntervals compared: {len(errors)} of {len(results)}")
        print(f"Mean absolute error: {sum(errors) / len(errors):.1f}%")
        print(f"Max absolute error:  {max(errors):.1f}%")
    else:
        print("\nNo overlapping window_metrics data found for any interval - "
              "was the capture engine running against this --db during the iperf3 test?")


def parse_args():
    parser = argparse.ArgumentParser(description="Compare capture-engine bandwidth against iperf3 ground truth")
    parser.add_argument("--json", required=True, help="Path to iperf3 -J output file")
    parser.add_argument("--db", default="netmon.db", help="SQLite database path")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    intervals = parse_ground_truth_json(args.json)
    conn = sqlite3.connect(args.db)
    windows = load_window_metrics(conn)
    conn.close()

    if not windows:
        print(f"Error: no window_metrics rows found in {args.db!r}. "
              f"Was the capture engine run against this database?")
    else:
        results = compare(intervals, windows)
        print_report(results)